openai:
  url: https://api.openai.com
  connection-timeout: 2s
  write-timeout: 10s
  read-timeout: 10s

server:
  port: 8081

spring:
  cloud:
    azure:
      keyvault:
        secret:
          endpoint: https://chat-service-key-vault.vault.azure.net/