# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mingo-chat-back

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Azure CLI script
      id: get-api-key
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo OPENAI_API_KEY=$(az keyvault secret show --vault-name chat-service-key-vault --name openai-api-key --query value --output tsv) >> $GITHUB_ENV

    - name: Print environment variable
      run: echo OPENAI_API_KEY


#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v2
#
#    - name: Log in to registry
#      uses: docker/login-action@v2
#      with:
#        registry: https://mingocontainerregistry.azurecr.io/
#        username: ${{ secrets.AzureAppService_ContainerUsername_d27f71f660cd4ed09af8423f91f9bbe0 }}
#        password: ${{ secrets.AzureAppService_ContainerPassword_28ea4fb9bcd4435681d3815617c89cdf }}
#
#    - name: Build and push container image to registry
#      uses: docker/build-push-action@v3
#      with:
#        push: true
#        tags: mingocontainerregistry.azurecr.io/chat-gpt-back:${{ github.sha }}
#        file: ./Dockerfile
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    environment:
#      name: 'production'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
#
#    steps:
#    - name: Deploy to Azure Web App
#      id: deploy-to-webapp
#      uses: azure/webapps-deploy@v2
#      with:
#        app-name: 'mingo-chat-back'
#        slot-name: 'production'
#        publish-profile: ${{ secrets.AzureAppService_PublishProfile_812742c8417a423580d91d080cd45412 }}
#        images: 'mingocontainerregistry.azurecr.io/chat-gpt-back:${{ github.sha }}'